<?php require_once('header.phtml'); ?>
<div class="hotCoffee">
    <h1>HotCoffee APP</h1>
    <div class="hotCoffeeForm">
        <form method="post" action="cook" name="addForm">
            <p>If you want to cook coffee fill the fields and press send</p>
            <label>Country<input type="text" name="country" placeholder="enter Spain or Italy"></label>
            <label>Syrup<input type="checkbox" name="syrup"></label>
            <label>Addition<input type="checkbox" name="addition"></label>
            <input type="submit" value="Send">
        </form>
    </div>
</div>
<?php require_once('footer.phtml'); ?>
